// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Envelope {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    #[prost(oneof = "envelope::Payload", tags = "2, 3, 4, 5, 6, 7, 8")]
    pub payload: ::core::option::Option<envelope::Payload>,
}
/// Nested message and enum types in `Envelope`.
pub mod envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "2")]
        HandshakeRequest(super::HandshakeRequest),
        #[prost(message, tag = "3")]
        HandshakeResponse(super::HandshakeResponse),
        #[prost(message, tag = "4")]
        Request(super::RuntimeRequest),
        #[prost(message, tag = "5")]
        Response(super::RuntimeResponse),
        #[prost(message, tag = "6")]
        Event(super::SessionEvent),
        #[prost(message, tag = "7")]
        HostToolRequest(super::HostToolRequest),
        #[prost(message, tag = "8")]
        HostToolResult(super::HostToolResult),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HandshakeRequest {
    #[prost(uint32, tag = "1")]
    pub minimum_version: u32,
    #[prost(uint32, tag = "2")]
    pub maximum_version: u32,
    #[prost(string, tag = "3")]
    pub client_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub client_version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HandshakeResponse {
    #[prost(uint32, tag = "1")]
    pub selected_version: u32,
    #[prost(string, tag = "2")]
    pub server_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub server_version: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "5")]
    pub error: ::core::option::Option<RuntimeError>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RuntimeRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(oneof = "runtime_request::Command", tags = "3, 4, 5, 6, 7, 8, 9, 10")]
    pub command: ::core::option::Option<runtime_request::Command>,
}
/// Nested message and enum types in `RuntimeRequest`.
pub mod runtime_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Command {
        #[prost(message, tag = "3")]
        Spawn(super::SpawnRequest),
        #[prost(message, tag = "4")]
        Resume(super::ResumeRequest),
        #[prost(message, tag = "5")]
        Prompt(super::PromptRequest),
        #[prost(message, tag = "6")]
        Steer(super::SteerRequest),
        #[prost(message, tag = "7")]
        FollowUp(super::FollowUpRequest),
        #[prost(message, tag = "8")]
        Interrupt(super::InterruptRequest),
        #[prost(message, tag = "9")]
        Close(super::CloseRequest),
        #[prost(message, tag = "10")]
        Status(super::StatusRequest),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RuntimeResponse {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(oneof = "runtime_response::Result", tags = "3, 4, 5, 6")]
    pub result: ::core::option::Option<runtime_response::Result>,
}
/// Nested message and enum types in `RuntimeResponse`.
pub mod runtime_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "3")]
        Ack(super::Ack),
        #[prost(message, tag = "4")]
        Spawned(super::SpawnedSession),
        #[prost(message, tag = "5")]
        Status(super::SessionStatus),
        #[prost(message, tag = "6")]
        Error(super::RuntimeError),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ack {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RuntimeError {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub retryable: bool,
    #[prost(bytes = "vec", tag = "4")]
    pub details_json: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostToolDefinition {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub input_schema_json: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpawnRequest {
    #[prost(string, tag = "1")]
    pub codex_thread_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub cwd: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub agent_dir: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub session_dir: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub thinking_level: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "8")]
    pub host_tools: ::prost::alloc::vec::Vec<HostToolDefinition>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResumeRequest {
    #[prost(string, tag = "1")]
    pub codex_thread_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_locator: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub cwd_override: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub host_tools: ::prost::alloc::vec::Vec<HostToolDefinition>,
    #[prost(string, tag = "5")]
    pub agent_dir: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PromptRequest {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SteerRequest {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FollowUpRequest {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InterruptRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpawnedSession {
    #[prost(string, tag = "1")]
    pub session_locator: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub thinking_level: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SessionStatus {
    #[prost(string, tag = "1")]
    pub state: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub token_usage: ::core::option::Option<TokenUsage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SessionEvent {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub sequence: u64,
    #[prost(
        oneof = "session_event::Event",
        tags = "3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18"
    )]
    pub event: ::core::option::Option<session_event::Event>,
}
/// Nested message and enum types in `SessionEvent`.
pub mod session_event {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "3")]
        AgentStart(super::AgentStart),
        #[prost(message, tag = "4")]
        TurnStart(super::TurnStart),
        #[prost(message, tag = "5")]
        MessageStart(super::MessageStart),
        #[prost(message, tag = "6")]
        TextDelta(super::MessageDelta),
        #[prost(message, tag = "7")]
        ThinkingDelta(super::MessageDelta),
        #[prost(message, tag = "8")]
        MessageEnd(super::MessageEnd),
        #[prost(message, tag = "9")]
        ToolExecutionStart(super::ToolExecutionStart),
        #[prost(message, tag = "10")]
        ToolExecutionUpdate(super::ToolExecutionUpdate),
        #[prost(message, tag = "11")]
        ToolExecutionEnd(super::ToolExecutionEnd),
        #[prost(message, tag = "12")]
        TurnEnd(super::TurnEnd),
        #[prost(message, tag = "13")]
        AgentEnd(super::AgentEnd),
        #[prost(message, tag = "14")]
        QueueUpdate(super::QueueUpdate),
        #[prost(message, tag = "15")]
        Compaction(super::CompactionEvent),
        #[prost(message, tag = "16")]
        Retry(super::RetryEvent),
        #[prost(message, tag = "17")]
        Error(super::ErrorEvent),
        #[prost(message, tag = "18")]
        TokenUsage(super::TokenUsage),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentStart {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TurnStart {
    #[prost(uint32, tag = "1")]
    pub turn_index: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageStart {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub role: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageDelta {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub content_index: u32,
    #[prost(string, tag = "3")]
    pub delta: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageEnd {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub role: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub message_json: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolExecutionStart {
    #[prost(string, tag = "1")]
    pub tool_call_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tool_name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub arguments_json: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolExecutionUpdate {
    #[prost(string, tag = "1")]
    pub tool_call_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tool_name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub partial_result_json: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolExecutionEnd {
    #[prost(string, tag = "1")]
    pub tool_call_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tool_name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub result_json: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "4")]
    pub is_error: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TurnEnd {
    #[prost(uint32, tag = "1")]
    pub turn_index: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub assistant_message_json: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentEnd {
    #[prost(string, tag = "1")]
    pub last_assistant_text: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub will_retry: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueueUpdate {
    #[prost(uint32, tag = "1")]
    pub steering_count: u32,
    #[prost(uint32, tag = "2")]
    pub follow_up_count: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompactionEvent {
    #[prost(string, tag = "1")]
    pub phase: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub aborted: bool,
    #[prost(string, tag = "4")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RetryEvent {
    #[prost(string, tag = "1")]
    pub phase: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub attempt: u32,
    #[prost(uint32, tag = "3")]
    pub maximum_attempts: u32,
    #[prost(uint64, tag = "4")]
    pub delay_ms: u64,
    #[prost(string, tag = "5")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub success: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ErrorEvent {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub retryable: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TokenUsage {
    #[prost(uint64, tag = "1")]
    pub input_tokens: u64,
    #[prost(uint64, tag = "2")]
    pub output_tokens: u64,
    #[prost(uint64, tag = "3")]
    pub cache_read_tokens: u64,
    #[prost(uint64, tag = "4")]
    pub cache_write_tokens: u64,
    #[prost(uint64, tag = "5")]
    pub total_tokens: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostToolRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub tool_call_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub tool_name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "5")]
    pub arguments_json: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostToolResult {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub tool_call_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub result_json: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "5")]
    pub error: ::core::option::Option<RuntimeError>,
}
