// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JsReplToolCallPayloadKind = "message_content" | "function_text" | "function_content_items" | "custom_text" | "mcp_result" | "mcp_error_result" | "error";
