// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsReplToolCallPayloadKind } from "./JsReplToolCallPayloadKind";

export type JsReplToolCallResponseSummary = { 
/**
 * Serialized `type` field from the raw response object, when available.
 */
response_type?: string, 
/**
 * High-level shape of the returned payload or rejection.
 */
payload_kind?: JsReplToolCallPayloadKind, 
/**
 * Truncated preview of textual payload content, if any.
 */
payload_text_preview?: string, 
/**
 * Untruncated byte length of the textual payload content, if any.
 */
payload_text_length?: number, 
/**
 * Number of top-level payload items when the payload is item-based.
 */
payload_item_count?: number, 
/**
 * Number of text items in a multimodal payload, when known.
 */
text_item_count?: number, 
/**
 * Number of image items in a multimodal payload, when known.
 */
image_item_count?: number, 
/**
 * Whether an MCP result included `structuredContent`.
 */
structured_content_present?: boolean, 
/**
 * Whether the nested tool payload itself reported an error.
 */
result_is_error?: boolean, };
