// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsReplToolCallResponseSummary } from "./JsReplToolCallResponseSummary";
import type { JsonValue } from "./serde_json/JsonValue";

export type JsReplToolCallResponseEvent = { 
/**
 * Identifier for the parent js_repl execution request.
 */
exec_id: string, 
/**
 * Identifier for the nested tool call made from js_repl.
 */
call_id: string, 
/**
 * Tool name passed to `codex.tool(...)`.
 */
tool_name: string, 
/**
 * Whether `codex.tool(...)` resolved (`true`) or rejected (`false`).
 */
ok: boolean, 
/**
 * Sanitized summary of the payload shape returned to JavaScript.
 */
summary: JsReplToolCallResponseSummary, 
/**
 * Serialized response object exactly as JavaScript receives it when the call resolves.
 */
response?: JsonValue, 
/**
 * Error string exactly as JavaScript receives it when the call rejects.
 */
error?: string, };
